#ifndef __MENU_H_
#define __MENU_H_



#define    STR_LANGUAGE_SET                             0x1         //语言选择
#define    STR_LANGUAGE_JT                              0x2         //简体中文
#define    STR_LANGUAGE_EN                              0x3         //English
#define    STR_LANGUAGE_FT                              0x4         //繁體中文
#define    STR_MENU_SYSTEM                              0x5         //系统设置
#define    STR_MENU_CONTRAST                            0x6         //对比调节
#define    STR_MENU_BACKLIGHT                           0x7         //背光时间
#define    STR_MENU_AUTOPOWER                           0x8         //定时关机
#define    STR_MENU_PLAYMODE                            0x9         //播放模式
#define    STR_MENU_FIRMWARE                            0xa         //固件版本
#define    STR_MENU_FACTORY                             0xb         //出厂设置
#define    STR_MENU_PARENTS_VOLUME                      0xc         //音量限制
#define    STR_MENU_PARENTS_WORK                        0xd         //工作时间
#define    STR_MENU_PARENTS_SLEEP                       0xe         //休眠时间
#define    STR_MENU_PARENTS_PASSWORD                    0xf         //密码设定
#define    STR_MENU_PASSWORD_SUCCEED                    0x10        //密码设置成功
#define    STR_MENU_PARENTS_BACK                        0x11        //返回
#define    STR_MENU_PASSWORD_OLD                        0x12        //请输入原密码
#define    STR_MENU_PASSWORD_NEW                        0x13        //请输入新密码
#define    STR_MENU_PASSWORD_RENEW                      0x14        //请再次输入新密码
#define    STR_MENU_PASSWORD_TWOERR                     0x15        //两次密码不一致
#define    STR_MENU_NAV                                 0x16        //主目录
#define    STR_MUSIC_REPEAT                             0x17        //复读模式
#define    STR_MENU_EQ                                  0x18        //音效
#define    STR_MENU_EXIT                                0x19        //退出
#define    STR_BACK_MENU                                0x1a        //返回主界面
#define    STR_BACKLIGHT_SET                            0x1b        //背光时间
#define    STR_BACKLIGHT_ALWAYS                         0x1c        //背光常亮
#define    STR_BACKLIGHT_5S                             0x1d        //延时5秒
#define    STR_BACKLIGHT_10S                            0x1e        //延时10秒
#define    STR_BACKLIGHT_15S                            0x1f        //延时15秒
#define    STR_BACKLIGHT_20S                            0x20        //延时20秒
#define    STR_BACKLIGHT_OFF                            0x21        //背光关闭
#define    STR_AUTOPOWER_OFF                            0x22        //关闭定时关机
#define    STR_AUTOPOWER_15M                            0x23        //延时15分钟
#define    STR_AUTOPOWER_30M                            0x24        //延时30分钟
#define    STR_AUTOPOWER_45M                            0x25        //延时45分钟
#define    STR_AUTOPOWER_60M                            0x26        //延时60分钟
#define    STR_PLAYMODE_SET                             0x27        //播放模式
#define    STR_PLAYMODE_ALL                             0x28        //全部循环
#define    STR_PLAYMODE_RE_FOLDER                       0x29        //目录循环
#define    STR_PLAYMODE_SINGLE                          0x2a        //单曲循环
#define    STR_PLAYMODE_RAMDOM                          0x2b        //随机播放
#define    STR_PLAYMODE_NORMAL                          0x2c        //普通模式
#define    STR_PLAYMODE_FOLDER                          0x2d        //目录播放
#define    STR_PLAYMODE_BROWSE                          0x2e        //浏览播放
#define    STR_MSG_TITLE                                0x2f        //提  示
#define    STR_MSG_OK                                   0x30        //确定
#define    STR_MSG_CANCEL                               0x31        //取消
#define    STR_MAIN_REPEATER                            0x32        //复 读 机
#define    STR_MAIN_MUSIC                               0x33        //音乐模式
#define    STR_MAIN_TAPE                                0x34        //磁 带 机
#define    STR_MAIN_AUX                                 0x35        //音源输入
#define    STR_MAIN_RECORDER                            0x36        //录 音 机
#define    STR_MAIN_VOICE                               0x37        //录音播放
#define    STR_MAIN_FM                                  0x38        //调频模式
#define    STR_MAIN_USB_DEVICE                          0x39        //USB设备
#define    STR_MAIN_SETTING                             0x3a        //系统设置
#define    STR_MAIN_PARENTS                             0x3b        //家长控制
#define    STR_MAIN_EBOOK                               0x3c        //电 子 书
#define    STR_MAIN_CLOCK                               0x3d        //日历
#define    STR_MAIN_NAV                                 0x3e        //文件管理
#define    STR_MAIN_LOUD_SPEAKER                        0x3f        //扩 音 器
#define    STR_MAIN_TOMCAT                              0x40        //汤 姆 猫
#define    STR_EQ_NORMAL                                0x41        //自然
#define    STR_EQ_POP                                   0x42        //流行
#define    STR_EQ_ROCK                                  0x43        //摇滚
#define    STR_EQ_JAZZ                                  0x44        //爵士
#define    STR_EQ_CLASSIC                               0x45        //古典
#define    STR_EQ_COUNTRY                               0x46        //乡村
#define    STR_EQ_BASS                                  0x47        //重低音
#define    STR_RECORD_SET                               0x48        //录音设置
#define    STR_RECORD_LOW                               0x49        //长时录音
#define    STR_RECORD_MID                               0x4a        //优质录音
#define    STR_RECORD_HIGH                              0x4b        //特级录音
#define    STR_VOLUME_SET                               0x4c        //音 量
#define    STR_MIX_STEP_SET                             0x4d        //混响级数
#define    STR_FIRMWARE_VERSION                         0x4e        //固件版本：v1.0.0
#define    STR_UPDATE_FW_CONFIRM                        0x4f        //是否升级固件版本？
#define    STR_FACTORY_CONFIRM                          0x50        //确定要恢复出厂设置吗？
#define    STR_FACTORY_SUCCESS                          0x51        //成功恢复出厂设置
#define    STR_DISCONNECTED_PC                          0x52        //未连接到电脑
#define    STR_USB_DEVICE_ERROR                         0x53        //USB设备错误
#define    STR_NO_DEVICE                                0x54        //未插入存储设备
#define    STR_INVALID_FAT                              0x55        //无效的文件系统
#define    STR_WRITE_DISABLE                            0x56        //无法写入存储设备
#define    STR_NO_MUSIC                                 0x57        //未找到音乐文件
#define    STR_NO_VOICE                                 0x58        //未找到录音文件
#define    STR_NO_EBOOK                                 0x59        //未找到文本文件
#define    STR_NO_CONNECTED_AUX                         0x5a        //未连接音频线
#define    STR_FILE_ERROR                               0x5b        //文件出错!
#define    STR_DISK_FULL                                0x5c        //磁盘已满!
#define    STR_MENU_DELETE                              0x5d        //删除文件
#define    STR_DELETE_ALL                               0x5e        //删除全部
#define    STR_DELETE_CONFIRM                           0x5f        //确定删除该文件吗？
#define    STR_DELETEALL_CONFIRM                        0x60        //确定删除所有文件吗？
#define    STR_DELETE_FAIL                              0x61        //删除失败
#define    STR_PASSWORD_ERROR                           0x62        //密码错误
#define    STR_WAITING                                  0x63        //请稍侯...
#define    STR_MODE_CHILD_WORK                          0x64        //状态：工作中
#define    STR_MODE_CHILD_SLEEP                         0x65        //状态：休眠中
#define    STR_NO_TAPE                                  0x66        //磁带机未按下
#define    STR_RECORDING                                0x67        //转录中...
#define    STR_FM_ERROR                                 0x68        //FM模块发生错误
#define    STR_UPDATEFILE_ERROR                         0x69        //升级文件打开错误
#define    STR_POWER_OFF                                0x6a        //已关机
#define    STR_FM_CHANNEL                               0x6b        //频道
#define    STR_FM_TOTAL                                 0x6c        //总数
#define    STR_TIME_SET                                 0x6d        //时间设置
#define    STR_ALARM_SET                                0x6e        //闹钟设置
#define    STR_ALARM_ON                                 0x6f        //闹钟开启
#define    STR_ALARM_OFF                                0x70        //闹钟关闭
#define    STR_ALARM_CYCLE                              0x71        //闹钟周期
#define    STR_ALARM_CYC_7D                             0x72        //每天
#define    STR_ALARM_CYC_5D                             0x73        //周一至周五
#define    STR_SUNDAY                                   0x74        //星期日
#define    STR_MONDAY                                   0x75        //星期一
#define    STR_TUESDAY                                  0x76        //星期二
#define    STR_WEDNESDAY                                0x77        //星期三
#define    STR_THURSDAY                                 0x78        //星期四
#define    STR_FRIDAY                                   0x79        //星期五
#define    STR_SATURDAY                                 0x7a        //星期六
#define    STR_ALARM_DELAY_CONFIRM                      0x7b        //闹铃时间
#define    STR_ALARM_MSG_OK                             0x7c        //重响
#define    STR_ALARM_MSG_CANCEL                         0x7d        //关闭
#define    STR_FM_RECIEVE                               0x7e        //收音
#define    STR_FM_DELETE                                0x7f        //删除电台
#define    STR_FM_DEL_ALL                               0x80        //删除全部电台
#define    STR_FM_STOP_SEEK                             0x81        //停止搜台
#define    STR_FM_AUTO_SEEK                             0x82        //自动搜索电台
#define    STR_POWEROFF                                 0x83        //关机
#define    STR_EBOOK_MODE                               0x84        //播放设定
#define    STR_EBOOK_SPEED                              0x85        //播放速度
#define    STR_EBOOK_HAND                               0x86        //手动播放
#define    STR_EBOOK_AUTO                               0x87        //自动播放
#define    STR_EBOOK_SELECT                             0x88        //文件选择
#define    STR_PLAY_SD                                  0x89        //SD卡
#define    STR_PLAY_TF                                  0x8a        //TF卡
#define    STR_PLAY_UDISK                               0x8b        //U盘
#define    STR_DEVICE_SELECT                            0x8c        //切换设备
#define    STR_MODE_SELECT                              0x8d        //切换模式
#define    STR_MODE_LEARN                               0x8e        //学习模式
#define    STR_MODE_SING                                0x8f        //演唱模式
#define    STR_MIC_VOLUME                               0x90        //话筒音量
#define    STR_ACCOMPANY_VOLUME                         0x91        //伴音音量
#define    STR_MAIN_VOLUME                              0x92        //主音量
#define    STR_KARAOKE                                  0x93        //卡拉ok
#define    STR_KARAOKE_ENTER                            0x94        //进入卡拉ok
#define    STR_KARAOKE_EXIT                             0x95        //退出卡拉ok
#define    STR_CARD_DIR                                 0x96        //插卡目录
#define    STR_UDISK_DIR                                0x97        //U盘目录
#define    STR_ALARM_MUSIC                              0x98        //闹钟音乐
#define    STR_ALMMUSIC_IN                              0x99        //内置铃声
#define    STR_ALMMUSIC_DISK                            0x9a        //磁盘音乐
#define    STR_LUNAR_MONTH_1                            0x9b        //年正月
#define    STR_LUNAR_MONTH_2                            0x9c        //年二月
#define    STR_LUNAR_MONTH_3                            0x9d        //年三月
#define    STR_LUNAR_MONTH_4                            0x9e        //年四月
#define    STR_LUNAR_MONTH_5                            0x9f        //年五月
#define    STR_LUNAR_MONTH_6                            0xa0        //年六月
#define    STR_LUNAR_MONTH_7                            0xa1        //年七月
#define    STR_LUNAR_MONTH_8                            0xa2        //年八月
#define    STR_LUNAR_MONTH_9                            0xa3        //年九月
#define    STR_LUNAR_MONTH_10                           0xa4        //年十月
#define    STR_LUNAR_MONTH_11                           0xa5        //年冬月
#define    STR_LUNAR_MONTH_12                           0xa6        //年腊月
#define    STR_LUNAR_DAY_1                              0xa7        //初一
#define    STR_LUNAR_DAY_2                              0xa8        //初二
#define    STR_LUNAR_DAY_3                              0xa9        //初三
#define    STR_LUNAR_DAY_4                              0xaa        //初四
#define    STR_LUNAR_DAY_5                              0xab        //初五
#define    STR_LUNAR_DAY_6                              0xac        //初六
#define    STR_LUNAR_DAY_7                              0xad        //初七
#define    STR_LUNAR_DAY_8                              0xae        //初八
#define    STR_LUNAR_DAY_9                              0xaf        //初九
#define    STR_LUNAR_DAY_10                             0xb0        //初十
#define    STR_LUNAR_DAY_11                             0xb1        //十一
#define    STR_LUNAR_DAY_12                             0xb2        //十二
#define    STR_LUNAR_DAY_13                             0xb3        //十三
#define    STR_LUNAR_DAY_14                             0xb4        //十四
#define    STR_LUNAR_DAY_15                             0xb5        //十五
#define    STR_LUNAR_DAY_16                             0xb6        //十六
#define    STR_LUNAR_DAY_17                             0xb7        //十七
#define    STR_LUNAR_DAY_18                             0xb8        //十八
#define    STR_LUNAR_DAY_19                             0xb9        //十九
#define    STR_LUNAR_DAY_20                             0xba        //二十
#define    STR_LUNAR_DAY_21                             0xbb        //廿一
#define    STR_LUNAR_DAY_22                             0xbc        //廿二
#define    STR_LUNAR_DAY_23                             0xbd        //廿三
#define    STR_LUNAR_DAY_24                             0xbe        //廿四
#define    STR_LUNAR_DAY_25                             0xbf        //廿五
#define    STR_LUNAR_DAY_26                             0xc0        //廿六
#define    STR_LUNAR_DAY_27                             0xc1        //廿七
#define    STR_LUNAR_DAY_28                             0xc2        //廿八
#define    STR_LUNAR_DAY_29                             0xc3        //廿九
#define    STR_LUNAR_DAY_30                             0xc4        //三十
#define    STR_YEAR_CALENDAR                            0xc5        //年
#define    STR_MONTH_CALENDAR                           0xc6        //月
#define    STR_DAY_CALENDAR                             0xc7        //日
#define    STR_FM_TIMEING_ON                            0xc8        //定时FM(开)
#define    STR_FM_TIMEING_OFF                           0xc9        //定时FM(关)
#define    STR_FM_TIME                                  0xca        //FM时间
#define    STR_FM_TIME_SET                              0xcb        //定时fm设置
#define    STR_FM_FRE_SET                               0xcc        //FM频率
#define    STR_SYS_TOOL                                 0xcd        //工具
#define    STR_SYS_TIME                                 0xce        //系统时间
#define    STR_ALARM_ON_SETTING                         0xcf        //闹钟(开)
#define    STR_ALARM_OFF_SETTING                        0xd0        //闹钟(关)
#define    STR_NO_SD                                    0xd1        //没插卡
#define    STR_NO_UDISK                                 0xd2        //没插U盘
#define    STR_MAIN_BT                                  0xd3        //蓝牙
#define    STR_BT_NOT_LINK                              0xd4        //蓝牙未连接
#define    STR_BT_DISCONNECT                            0xd5        //断开连接
#define    STR_BT_RECONNECT                             0xd6        //最近设备重连
#define    STR_BT_LIST_CONNECTED                        0xd7        //连接设备列表
#define    STR_BT_DEL_PAIRED                            0xd8        //删除配对信息
#define    STR_BT_INFO                                  0xd9        //设备信息
#define    STR_BT_CONNECTING                            0xda        //连接中...
#define    STR_BT_FAIL_CONNECT                          0xdb        //连接失败
#define    STR_BT_CONNECTED                             0xdc        //蓝牙已连接
#define    STR_BT_PHONEBOOK                             0xdd        //电话本
#define    STR_BT_CONTACTS                              0xde        //联系人
#define    STR_BT_NO_CONTACTS                           0xdf        //无联系人，请同步
#define    STR_BT_SYNC_CONTACTS                         0xe0        //同步联系人
#define    STR_BT_SYNC_WAITING                          0xe1        //同步中，请稍候...
#define    STR_BT_SYNC_SUCCESS                          0xe2        //同步成功
#define    STR_BT_SYNC_FAIL                             0xe3        //同步失败
#define    STR_BT_SYNC_STOP                             0xe4        //同步中止
#define    STR_BT_DELETE_ALL_CONTACTS                   0xe5        //删除所有联系人
#define    STR_BT_CONFIRM_DELETE_CONTACTS               0xe6        //确定删除所有联系人？
#define    STR_BT_DELETE_CONTACTS_SUCCESS               0xe7        //删除所有联系人成功



#endif
