#ifndef RES_H

#define RES_H


//	.\BIGNUM\  
#define RES_BIGNUM_0_BMP          			0x0
#define RES_BIGNUM_1_BMP          			0x1
#define RES_BIGNUM_2_BMP          			0x2
#define RES_BIGNUM_3_BMP          			0x3
#define RES_BIGNUM_4_BMP          			0x4
#define RES_BIGNUM_5_BMP          			0x5
#define RES_BIGNUM_6_BMP          			0x6
#define RES_BIGNUM_7_BMP          			0x7
#define RES_BIGNUM_8_BMP          			0x8
#define RES_BIGNUM_9_BMP          			0x9
#define RES_BIGNUM_COLON_BMP      			0xa

//	.\  
#define RES_BOX_BMP               			0xb

//	.\ICON\  
#define RES_ICON_A_BMP            			0xc
#define RES_ICON_A2B_BMP          			0xd
#define RES_ICON_AB_BMP           			0xe
#define RES_ICON_ALM_BMP          			0xf
#define RES_ICON_B_BMP            			0x10
#define RES_ICON_BAT0_BMP         			0x11
#define RES_ICON_BAT1_BMP         			0x12
#define RES_ICON_BAT2_BMP         			0x13
#define RES_ICON_BAT3_BMP         			0x14
#define RES_ICON_BAT4_BMP         			0x15
#define RES_ICON_CONTRSTW_BMP     			0x16
#define RES_ICON_FILE_BMP         			0x17
#define RES_ICON_FILE_MUSIC_BMP   			0x18
#define RES_ICON_FOCUSL_BMP       			0x19
#define RES_ICON_FOCUSR_BMP       			0x1a
#define RES_ICON_FOLDERC_BMP      			0x1b
#define RES_ICON_FOLDER_UP_BMP    			0x1c
#define RES_ICON_ITEM_BMP         			0x1d
#define RES_ICON_MP3_000_BMP      			0x1e
#define RES_ICON_MP3_032_BMP      			0x1f
#define RES_ICON_MP3_064_BMP      			0x20
#define RES_ICON_MP3_096_BMP      			0x21
#define RES_ICON_MP3_128_BMP      			0x22
#define RES_ICON_MP3_192_BMP      			0x23
#define RES_ICON_MP3_256_BMP      			0x24
#define RES_ICON_MUSIC_FILE_BMP   			0x25
#define RES_ICON_NO_FILE_BMP      			0x26
#define RES_ICON_PALYING_BMP      			0x27
#define RES_ICON_PLAY_MODE0_BMP   			0x28
#define RES_ICON_PLAY_MODE1_BMP   			0x29
#define RES_ICON_PLAY_MODE2_BMP   			0x2a
#define RES_ICON_PLAY_MODE3_BMP   			0x2b
#define RES_ICON_REC_BMP          			0x2c
#define RES_ICON_SDCARD_BMP       			0x2d
#define RES_ICON_SDCARD1_BMP      			0x2e
#define RES_ICON_STOP_BMP         			0x2f
#define RES_ICON_UDISK_BMP        			0x30
#define RES_ICON_UDISK1_BMP       			0x31
#define RES_ICON_UNKOWN_FILE_BMP  			0x32
#define RES_ICON_VOL1_BMP         			0x33

//	.\  
#define RES_LINE_BMP              			0x34

//	.\MAIN\  
#define RES_MAIN_AUX0_BMP         			0x35
#define RES_MAIN_AUX1_BMP         			0x36
#define RES_MAIN_AUX2_BMP         			0x37
#define RES_MAIN_AUX3_BMP         			0x38
#define RES_MAIN_BT0_BMP          			0x39
#define RES_MAIN_BT1_BMP          			0x3a
#define RES_MAIN_BT2_BMP          			0x3b
#define RES_MAIN_BT3_BMP          			0x3c
#define RES_MAIN_DICT0_BMP        			0x3d
#define RES_MAIN_EBOOK0_BMP       			0x3e
#define RES_MAIN_EBOOK1_BMP       			0x3f
#define RES_MAIN_EBOOK2_BMP       			0x40
#define RES_MAIN_EBOOK3_BMP       			0x41
#define RES_MAIN_EXPLORER0_BMP    			0x42
#define RES_MAIN_GAME0_BMP        			0x43
#define RES_MAIN_MIC0_BMP         			0x44
#define RES_MAIN_MIC1_BMP         			0x45
#define RES_MAIN_MIC2_BMP         			0x46
#define RES_MAIN_MIC3_BMP         			0x47
#define RES_MAIN_MUSIC0_BMP       			0x48
#define RES_MAIN_MUSIC1_BMP       			0x49
#define RES_MAIN_MUSIC2_BMP       			0x4a
#define RES_MAIN_MUSIC3_BMP       			0x4b
#define RES_MAIN_PARENTS0_BMP     			0x4c
#define RES_MAIN_PARENTS1_BMP     			0x4d
#define RES_MAIN_PARENTS2_BMP     			0x4e
#define RES_MAIN_PARENTS3_BMP     			0x4f
#define RES_MAIN_RADIO0_BMP       			0x50
#define RES_MAIN_RADIO1_BMP       			0x51
#define RES_MAIN_RADIO2_BMP       			0x52
#define RES_MAIN_RADIO3_BMP       			0x53
#define RES_MAIN_RTC0_BMP         			0x54
#define RES_MAIN_RTC1_BMP         			0x55
#define RES_MAIN_RTC2_BMP         			0x56
#define RES_MAIN_RTC3_BMP         			0x57
#define RES_MAIN_SPEARKER0_BMP    			0x58
#define RES_MAIN_SPEARKER1_BMP    			0x59
#define RES_MAIN_SPEARKER2_BMP    			0x5a
#define RES_MAIN_SPEARKER3_BMP    			0x5b
#define RES_MAIN_SYSTEM0_BMP      			0x5c
#define RES_MAIN_SYSTEM1_BMP      			0x5d
#define RES_MAIN_SYSTEM2_BMP      			0x5e
#define RES_MAIN_SYSTEM3_BMP      			0x5f
#define RES_MAIN_TAPE0_BMP        			0x60
#define RES_MAIN_TAPE1_BMP        			0x61
#define RES_MAIN_TAPE2_BMP        			0x62
#define RES_MAIN_TAPE3_BMP        			0x63
#define RES_MAIN_TOMCAT0_BMP      			0x64
#define RES_MAIN_TOMCAT1_BMP      			0x65
#define RES_MAIN_TOMCAT2_BMP      			0x66
#define RES_MAIN_TOMCAT3_BMP      			0x67
#define RES_MAIN_USB0_BMP         			0x68
#define RES_MAIN_USB1_BMP         			0x69
#define RES_MAIN_USB2_BMP         			0x6a
#define RES_MAIN_USB3_BMP         			0x6b
#define RES_MAIN_VOICE0_BMP       			0x6c
#define RES_MAIN_VOICE1_BMP       			0x6d
#define RES_MAIN_VOICE2_BMP       			0x6e
#define RES_MAIN_VOICE3_BMP       			0x6f

//	.\MAIN_S\  
#define RES_MAIN_S_AUX1_BMP       			0x70
#define RES_MAIN_S_AUXA_BMP       			0x71
#define RES_MAIN_S_BT_BMP         			0x72
#define RES_MAIN_S_BTA_BMP        			0x73
#define RES_MAIN_S_EBOOK_BMP      			0x74
#define RES_MAIN_S_EBOOKA_BMP     			0x75
#define RES_MAIN_S_FM_BMP         			0x76
#define RES_MAIN_S_FMA_BMP        			0x77
#define RES_MAIN_S_MIC_BMP        			0x78
#define RES_MAIN_S_MICA_BMP       			0x79
#define RES_MAIN_S_MUSIC_BMP      			0x7a
#define RES_MAIN_S_MUSICA_BMP     			0x7b
#define RES_MAIN_S_RTC_BMP        			0x7c
#define RES_MAIN_S_RTCA_BMP       			0x7d
#define RES_MAIN_S_SPEAK_BMP      			0x7e
#define RES_MAIN_S_SPEAKA_BMP     			0x7f
#define RES_MAIN_S_SYSTEM_BMP     			0x80
#define RES_MAIN_S_SYSTEMA_BMP    			0x81
#define RES_MAIN_S_TAPE_BMP       			0x82
#define RES_MAIN_S_TAPEA_BMP      			0x83
#define RES_MAIN_S_USBAUDIO_BMP   			0x84
#define RES_MAIN_S_USBAUDIOA_BMP  			0x85
#define RES_MAIN_S_VOICE_BMP      			0x86
#define RES_MAIN_S_VOICEA_BMP     			0x87

//	.\MASS\  
#define RES_MASS_IDLE_BMP         			0x88
#define RES_MASS_READ_BMP         			0x89
#define RES_MASS_WRITE_BMP        			0x8a

//	.\MEDIUMNUM\  
#define RES_MEDIUMNUM_0_BMP       			0x8b
#define RES_MEDIUMNUM_1_BMP       			0x8c
#define RES_MEDIUMNUM_2_BMP       			0x8d
#define RES_MEDIUMNUM_3_BMP       			0x8e
#define RES_MEDIUMNUM_4_BMP       			0x8f
#define RES_MEDIUMNUM_5_BMP       			0x90
#define RES_MEDIUMNUM_6_BMP       			0x91
#define RES_MEDIUMNUM_7_BMP       			0x92
#define RES_MEDIUMNUM_8_BMP       			0x93
#define RES_MEDIUMNUM_9_BMP       			0x94
#define RES_MEDIUMNUM_COLON_BMP   			0x95
#define RES_MEDIUMNUM_CP_SPRIT_BMP			0x96

//	.\OCX\  
#define RES_OCX_BAR_BMP           			0x97
#define RES_OCX_FMG_BMP           			0x98
#define RES_OCX_FMQT_BMP          			0x99
#define RES_OCX_INDEX_BMP         			0x9a
#define RES_OCX_PASSBOX1_BMP      			0x9b
#define RES_OCX_PASSBOX2_BMP      			0x9c
#define RES_OCX_PASSBOX3_BMP      			0x9d
#define RES_OCX_PASSBOX4_BMP      			0x9e
#define RES_OCX_PASSBOX_V_BMP     			0x9f

//	.\PLAY\  
#define RES_PLAY_CP_LRC_0_BMP     			0xa0
#define RES_PLAY_CP_SDCARD_BMP    			0xa1
#define RES_PLAY_CP_UDISK_BMP     			0xa2
#define RES_PLAY_EQ_0_BMP         			0xa3
#define RES_PLAY_EQ_1_BMP         			0xa4
#define RES_PLAY_EQ_2_BMP         			0xa5
#define RES_PLAY_EQ_3_BMP         			0xa6
#define RES_PLAY_EQ_4_BMP         			0xa7
#define RES_PLAY_EQ_5_BMP         			0xa8
#define RES_PLAY_EQ_6_BMP         			0xa9
#define RES_PLAY_M_TYPE1_BMP      			0xaa
#define RES_PLAY_M_TYPE2_BMP      			0xab
#define RES_PLAY_M_TYPE3_BMP      			0xac
#define RES_PLAY_PLAY_MODE0_BMP   			0xad
#define RES_PLAY_PLAY_MODE1_BMP   			0xae
#define RES_PLAY_PLAY_MODE2_BMP   			0xaf
#define RES_PLAY_PLAY_MODE3_BMP   			0xb0
#define RES_PLAY_PLAY_MODE4_BMP   			0xb1
#define RES_PLAY_PLAY_MODE5_BMP   			0xb2
#define RES_PLAY_RECODEFA_BMP     			0xb3
#define RES_PLAY_SPEED_0_BMP      			0xb4
#define RES_PLAY_SPEED_1_BMP      			0xb5
#define RES_PLAY_SPEED_2_BMP      			0xb6
#define RES_PLAY_SPEED_3_BMP      			0xb7
#define RES_PLAY_SPEED_4_BMP      			0xb8
#define RES_PLAY_SPEED_5_BMP      			0xb9
#define RES_PLAY_SPEED_6_BMP      			0xba
#define RES_PLAY_SPEED_7_BMP      			0xbb
#define RES_PLAY_SPEED_8_BMP      			0xbc
#define RES_PLAY_SPEED_9_BMP      			0xbd
#define RES_PLAY_STATUS_0_BMP     			0xbe
#define RES_PLAY_STATUS_1_BMP     			0xbf
#define RES_PLAY_STATUS_2_BMP     			0xc0
#define RES_PLAY_STATUS_3_BMP     			0xc1
#define RES_PLAY_STATUS_4_BMP     			0xc2
#define RES_PLAY_STATUS_5_BMP     			0xc3
#define RES_PLAY_STATUS_6_BMP     			0xc4
#define RES_PLAY_STATUS_7_BMP     			0xc5
#define RES_PLAY_STATUS_70_BMP    			0xc6
#define RES_PLAY_STATUS_71_BMP    			0xc7
#define RES_PLAY_STATUS_72_BMP    			0xc8
#define RES_PLAY_STATUS_73_BMP    			0xc9
#define RES_PLAY_STATUS_74_BMP    			0xca
#define RES_PLAY_STATUS_75_BMP    			0xcb
#define RES_PLAY_STATUS_76_BMP    			0xcc
#define RES_PLAY_STATUS_77_BMP    			0xcd

//	.\POWEROFF\  
#define RES_POWEROFF_BYEBYE0_BMP  			0xce
#define RES_POWEROFF_END0_BMP     			0xcf
#define RES_POWEROFF_END1_BMP     			0xd0
#define RES_POWEROFF_END2_BMP     			0xd1
#define RES_POWEROFF_END3_BMP     			0xd2
#define RES_POWEROFF_END4_BMP     			0xd3
#define RES_POWEROFF_END5_BMP     			0xd4
#define RES_POWEROFF_END6_BMP     			0xd5
#define RES_POWEROFF_END7_BMP     			0xd6
#define RES_POWEROFF_END8_BMP     			0xd7
#define RES_POWEROFF_END9_BMP     			0xd8
#define RES_POWEROFF_END90_BMP    			0xd9
#define RES_POWEROFF_END91_BMP    			0xda
#define RES_POWEROFF_END92_BMP    			0xdb
#define RES_POWEROFF_END93_BMP    			0xdc

//	.\POWERON\  
#define RES_POWERON_BOOT1_BMP     			0xdd
#define RES_POWERON_WELCOME_BMP   			0xde

//	.\RECORD\  
#define RES_RECORD_LINEIN_BMP     			0xdf
#define RES_RECORD_REC0_BMP       			0xe0
#define RES_RECORD_REC1_BMP       			0xe1
#define RES_RECORD_REC2_BMP       			0xe2
#define RES_RECORD_REC3_BMP       			0xe3

//	.\  
#define RES_SELECTED_BMP          			0xe4
#define RES_SING_BMP              			0xe5

//	.\SMALLNUM\  
#define RES_SMALLNUM_0_BMP        			0xe6
#define RES_SMALLNUM_1_BMP        			0xe7
#define RES_SMALLNUM_2_BMP        			0xe8
#define RES_SMALLNUM_3_BMP        			0xe9
#define RES_SMALLNUM_4_BMP        			0xea
#define RES_SMALLNUM_5_BMP        			0xeb
#define RES_SMALLNUM_6_BMP        			0xec
#define RES_SMALLNUM_7_BMP        			0xed
#define RES_SMALLNUM_8_BMP        			0xee
#define RES_SMALLNUM_9_BMP        			0xef
#define RES_SMALLNUM_COLON_BMP    			0xf0
#define RES_SMALLNUM_SS_BMP       			0xf1
#define RES_SMALLNUM_SS0_BMP      			0xf2
#define RES_SMALLNUM_SS1_BMP      			0xf3
#define RES_SMALLNUM_SS2_BMP      			0xf4
#define RES_SMALLNUM_SS3_BMP      			0xf5
#define RES_SMALLNUM_SS4_BMP      			0xf6
#define RES_SMALLNUM_SS5_BMP      			0xf7
#define RES_SMALLNUM_SS6_BMP      			0xf8
#define RES_SMALLNUM_SS7_BMP      			0xf9
#define RES_SMALLNUM_SS8_BMP      			0xfa
#define RES_SMALLNUM_SS9_BMP      			0xfb

//	.\  
#define RES_STATUS0_BMP           			0xfc
#define RES_STATUS1_BMP           			0xfd
#define RES_STATUS2_BMP           			0xfe
#define RES_STATUS3_BMP           			0xff
#define RES_STATUS4_BMP           			0x100
#define RES_STATUS5_BMP           			0x101
#define RES_STATUS_X_BMP          			0x102

#endif
