#ifndef RES_H

#define RES_H


//	.\BIGNUM\  
#define RES_BIGNUM_0_BMP          			0x0
#define RES_BIGNUM_1_BMP          			0x1
#define RES_BIGNUM_2_BMP          			0x2
#define RES_BIGNUM_3_BMP          			0x3
#define RES_BIGNUM_4_BMP          			0x4
#define RES_BIGNUM_5_BMP          			0x5
#define RES_BIGNUM_6_BMP          			0x6
#define RES_BIGNUM_7_BMP          			0x7
#define RES_BIGNUM_8_BMP          			0x8
#define RES_BIGNUM_9_BMP          			0x9
#define RES_BIGNUM_COLON_BMP      			0xa

//	.\  
#define RES_BOX_BMP               			0xb

//	.\ICON\  
#define RES_ICON_A_BMP            			0xc
#define RES_ICON_A2B_BMP          			0xd
#define RES_ICON_AB_BMP           			0xe
#define RES_ICON_ALM_BMP          			0xf
#define RES_ICON_B_BMP            			0x10
#define RES_ICON_BAT0_BMP         			0x11
#define RES_ICON_BAT1_BMP         			0x12
#define RES_ICON_BAT2_BMP         			0x13
#define RES_ICON_BAT3_BMP         			0x14
#define RES_ICON_BAT4_BMP         			0x15
#define RES_ICON_FOCUSL_BMP       			0x16
#define RES_ICON_FOCUSR_BMP       			0x17
#define RES_ICON_FOLDERC_BMP      			0x18
#define RES_ICON_FOLDER_UP_BMP    			0x19
#define RES_ICON_ITEM_BMP         			0x1a
#define RES_ICON_MP3_064_BMP      			0x1b
#define RES_ICON_MP3_096_BMP      			0x1c
#define RES_ICON_MP3_128_BMP      			0x1d
#define RES_ICON_REC_BMP          			0x1e
#define RES_ICON_STOP_BMP         			0x1f
#define RES_ICON_UDISK_BMP        			0x20
#define RES_ICON_UDISK1_BMP       			0x21
#define RES_ICON_VOL_BMP          			0x22

//	.\  
#define RES_LINE_BMP              			0x23

//	.\MAIN\  
#define RES_MAIN_BT0_BMP          			0x24
#define RES_MAIN_BT1_BMP          			0x25
#define RES_MAIN_BT2_BMP          			0x26
#define RES_MAIN_BT3_BMP          			0x27

//	.\MASS\  
#define RES_MASS_IDLE_BMP         			0x28
#define RES_MASS_READ_BMP         			0x29
#define RES_MASS_WRITE_BMP        			0x2a

//	.\MEDIUMNUM\  
#define RES_MEDIUMNUM_0_BMP       			0x2b
#define RES_MEDIUMNUM_1_BMP       			0x2c
#define RES_MEDIUMNUM_2_BMP       			0x2d
#define RES_MEDIUMNUM_3_BMP       			0x2e
#define RES_MEDIUMNUM_4_BMP       			0x2f
#define RES_MEDIUMNUM_5_BMP       			0x30
#define RES_MEDIUMNUM_6_BMP       			0x31
#define RES_MEDIUMNUM_7_BMP       			0x32
#define RES_MEDIUMNUM_8_BMP       			0x33
#define RES_MEDIUMNUM_9_BMP       			0x34
#define RES_MEDIUMNUM_COLON_BMP   			0x35
#define RES_MEDIUMNUM_CP_SPRIT_BMP			0x36

//	.\OCX\  
#define RES_OCX_BAR_BMP           			0x37
#define RES_OCX_FMG_BMP           			0x38
#define RES_OCX_FMQT_BMP          			0x39
#define RES_OCX_INDEX_BMP         			0x3a
#define RES_OCX_PASSBOX1_BMP      			0x3b
#define RES_OCX_PASSBOX2_BMP      			0x3c
#define RES_OCX_PASSBOX3_BMP      			0x3d
#define RES_OCX_PASSBOX4_BMP      			0x3e
#define RES_OCX_PASSBOX_V_BMP     			0x3f

//	.\PLAY\  
#define RES_PLAY_CP_LRC_0_BMP     			0x40
#define RES_PLAY_CP_SDCARD_BMP    			0x41
#define RES_PLAY_CP_UDISK_BMP     			0x42
#define RES_PLAY_EQ_0_BMP         			0x43
#define RES_PLAY_EQ_1_BMP         			0x44
#define RES_PLAY_EQ_2_BMP         			0x45
#define RES_PLAY_EQ_3_BMP         			0x46
#define RES_PLAY_EQ_4_BMP         			0x47
#define RES_PLAY_EQ_5_BMP         			0x48
#define RES_PLAY_EQ_6_BMP         			0x49
#define RES_PLAY_M_TYPE1_BMP      			0x4a
#define RES_PLAY_M_TYPE2_BMP      			0x4b
#define RES_PLAY_M_TYPE3_BMP      			0x4c
#define RES_PLAY_PLAY_MODE0_BMP   			0x4d
#define RES_PLAY_PLAY_MODE1_BMP   			0x4e
#define RES_PLAY_PLAY_MODE2_BMP   			0x4f
#define RES_PLAY_PLAY_MODE3_BMP   			0x50

//	.\POWEROFF\  
#define RES_POWEROFF_BYEBYE0_BMP  			0x51

//	.\POWERON\  
#define RES_POWERON_WELCOME_BMP   			0x52

//	.\RECORD\  
#define RES_RECORD_LINEIN_BMP     			0x53
#define RES_RECORD_REC0_BMP       			0x54

//	.\  
#define RES_SELECTED_BMP          			0x55

//	.\SMALLNUM\  
#define RES_SMALLNUM_0_BMP        			0x56
#define RES_SMALLNUM_1_BMP        			0x57
#define RES_SMALLNUM_2_BMP        			0x58
#define RES_SMALLNUM_3_BMP        			0x59
#define RES_SMALLNUM_4_BMP        			0x5a
#define RES_SMALLNUM_5_BMP        			0x5b
#define RES_SMALLNUM_6_BMP        			0x5c
#define RES_SMALLNUM_7_BMP        			0x5d
#define RES_SMALLNUM_8_BMP        			0x5e
#define RES_SMALLNUM_9_BMP        			0x5f
#define RES_SMALLNUM_COLON_BMP    			0x60
#define RES_SMALLNUM_SS_BMP       			0x61
#define RES_SMALLNUM_SS0_BMP      			0x62
#define RES_SMALLNUM_SS1_BMP      			0x63
#define RES_SMALLNUM_SS2_BMP      			0x64
#define RES_SMALLNUM_SS3_BMP      			0x65
#define RES_SMALLNUM_SS4_BMP      			0x66
#define RES_SMALLNUM_SS5_BMP      			0x67
#define RES_SMALLNUM_SS6_BMP      			0x68
#define RES_SMALLNUM_SS7_BMP      			0x69
#define RES_SMALLNUM_SS8_BMP      			0x6a
#define RES_SMALLNUM_SS9_BMP      			0x6b

//	.\  
#define RES_STATUS0_BMP           			0x6c
#define RES_STATUS1_BMP           			0x6d
#define RES_STATUS_X_BMP          			0x6e

#endif
